project:
  type: website
  output-dir: docs

website:
  title: "Gapminder Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: life-gdp.qmd
        text: Life Expectancy & GDP
      - href: life-population.qmd
        text: Life Expectancy & Population
      - href: country.qmd
        text: Country Analysis
  page-footer:
    left: "© 2025 Jacky An"
    right: "Built with Quarto"

format:
  html:
    theme: lumen  # Change to any preferred theme
    toc: true
